<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<?php

?>

<form action="probando2.php" method="post">

    <label class="label" for="fecha_con">Fecha de congelado</label>
        <input type="date" name="fecha_con" id="fecha_con" value="">
    
  
		<input type="submit" value="Añadir" name="btn_anadir_ali">
							
    </form>
                


    
</body>
</html>